azure:
  storage:
      connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;

logging:
  level:
    root: INFO
    com:
      example: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB